runtime:
  cache_dir: ./.cache/antora

site:
  title: "Workshop Service Mesh"
  url: https://github.com/dbgjerez/workshop-service-mesh-doc
  start_page: index.adoc

content:
  sources:
    - url: git@github.com:dbgjerez/workshop-service-mesh-doc
      tags: []
      branches: [master]
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  clean: true
  dir: ./gh-pages
